M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date Sun 07 Aug 2022 22:42:25 BST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-07T22:42:25+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X4.5089Y-2.196
T0
M30
